system {
    host-name switch;
    root-authentication {
        plain-text-password-value "redhat";
    }
    auto-image-upgrade {
        disable;
    }
    services {
        ssh;
    }
    syslog {
        console {
            any critical;
        }
    }
}

interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.122.10/24;
            }
        }
    }
}
